### PR TITLE
[MSHARED-922] remove checksum calculation from ProjectDeployer

### PR DESCRIPTION
**Pull request by kwin**
The checksums are generated in aether/maven-resolver

### CODE REVIEW

**Comment by michael-o** [comment]
I wonder whether this could affect older Maven versions which update to a plugin with this shared component version.

**Comment by kwin** [comment]
The relevant IT is executed with Maven 3.0.5 and newer (https://github.com/apache/maven-artifact-transfer/blob/87842f9c712eb6496b32d4aff09307d0970d9f7b/src/it/maven-project-deployer-plugin/src/test/java/org/apache/maven/plugin/project/deploy/ProjectDeployerTest.java#L45) and explicitly tests for checksums. This IT still works even after removing checksum generation from this module (because both Aether for Maven < 3.1 and Maven Resolver for 3.1+ generate the necessary checksums)

**Comment by michael-o** [comment]
Makes sense. I'll run all tests on Jenkins. @rfscholte @khmarbaise opinions?

**Comment by rfscholte** [comment]
It confirms my expectations: checksums are indeed generated by Aether/Artifact Resolver and not anymore required in the plugins or artifact-transfer.

**Comment by michael-o** [comment]
So we are good to merge here...?

**Pull request closed without merging**
