### PR TITLE
MSHARED-869 - extract parameter validation logic

### PR DESCRIPTION
**Pull request by pzygielo**
Avoid duplication of _The parameter root is not allowed to be null._ literal.

### CODE REVIEW

**Comment by khmarbaise** [comment]
Looks good so far...

**Comment by pzygielo** [comment]
I can't see build fired for PR at https://builds.apache.org/job/maven-box/job/maven-artifact-transfer/  but locally
```
mvn -P run-its clean verify
```
completes with success.

**Comment by khmarbaise** [comment]
You will not see it firing cause it's not triggered on Apache side...and it will never be...could you please squash your commits into a single one and can you create a JIRA issue for that so I appreciate to merge that...and make the commit message following 
```
MSHARED-XXX - Headline
Optional explanations
```
Thank you for your support.

**Comment by pzygielo** [comment]
@khmarbaise - thanks for checking.

Commits squashed and reference to JIRA id added.

**Comment by khmarbaise** [comment]
So lets see what CI says https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-artifact-transfer/job/MSHARED-869/

**Comment by khmarbaise** [comment]
Merged to master. Thanks for your contribution.

**Pull request closed without merging**
